settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: twitter
  path: .
  commands:
    install:
      status: true
      method: go build -o twitter
    run:
      status: true
      method: ./twitter
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
    scripts:
    - type: before
      command: wire ./...
      global: true
      output: true