version: "3.7"

services:
  app:
    build:
      context: .
    ports:
      - 127.0.0.1:18888:80
    volumes:
      - .:/go/src/golang-odai
    working_dir: /go/src/golang-odai
    depends_on:
      - db
    env_file:
      - ./secret.env

  db:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 127.0.0.1:43306:3306
    hostname: db

  init:
    image: mysql:5.7
    volumes:
      - ./db:/work
    working_dir: /work
    depends_on:
      - db
    command:
      - ./init.sh

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: trace
    ports:
      - 127.0.0.1:16686:16686